### ISSUE TITLE
When can create next round?

### ISSUE THREAD

**Issue by Mlody87** [rmoritz/swissdutch#3]
Hi,
Thank you for your work!
I know you wrote it a long time ago but I have a question for you. I have the impression that this pairing aims to get a winner so sometimes it happens that with 5 players it is possible to pair only 2 rounds. Is there any possibility of checking whether further pairing is possible? Now just the engine throws an exception.
Is there possibility to force pairing next round?

**Comment by rmoritz** [comment]
Hi @Mlody87, unfortunately I don't have the time (or inclination TBH) to work on this library any more. You are welcome to fork this repo and make any improvements or changes you so desire :smiley:.

**Comment by Mlody87** [comment]
Thanks:)
